name: project
dependencies:
  - python=3.7
  - pytorch=1.5.0
  - matplotlib
  - numpy
  - nltk
  - pandas
  - scikit-learn
  - scipy
  - skorch
  - dill
  - pip
  - pip:
    - datetime
    - quickumls